[2024-01-24T03:06:21.923+0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-01-23T18:55:33.041952+00:00 [queued]>
[2024-01-24T03:06:21.987+0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-01-23T18:55:33.041952+00:00 [queued]>
[2024-01-24T03:06:21.988+0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T03:06:21.988+0800] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2024-01-24T03:06:21.988+0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T03:06:22.048+0800] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): train_model> on 2024-01-23 18:55:33.041952+00:00
[2024-01-24T03:06:22.072+0800] {standard_task_runner.py:55} INFO - Started process 87908 to run task
[2024-01-24T03:06:22.078+0800] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2024-01-23T18:55:33.041952+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp_vw7ed66']
[2024-01-24T03:06:22.080+0800] {standard_task_runner.py:83} INFO - Job 31: Subtask train_model
[2024-01-24T03:06:22.426+0800] {task_command.py:389} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2024-01-23T18:55:33.041952+00:00 [running]> on host ml
[2024-01-24T03:06:22.675+0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=youtube_comments_score
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-01-23T18:55:33.041952+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-23T18:55:33.041952+00:00
[2024-01-24T03:06:22.677+0800] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-24T03:06:22.678+0800] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/am/project/scripts/train_model.py']
[2024-01-24T03:06:22.697+0800] {subprocess.py:86} INFO - Output:
[2024-01-24T03:06:24.435+0800] {subprocess.py:93} INFO - /home/am/project/scripts/train_model.py:3: DeprecationWarning:
[2024-01-24T03:06:24.435+0800] {subprocess.py:93} INFO - Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
[2024-01-24T03:06:24.435+0800] {subprocess.py:93} INFO - (to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
[2024-01-24T03:06:24.436+0800] {subprocess.py:93} INFO - but was not found to be installed on your system.
[2024-01-24T03:06:24.436+0800] {subprocess.py:93} INFO - If this would cause problems for you,
[2024-01-24T03:06:24.436+0800] {subprocess.py:93} INFO - please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
[2024-01-24T03:06:24.436+0800] {subprocess.py:93} INFO - 
[2024-01-24T03:06:24.436+0800] {subprocess.py:93} INFO -   import pandas as pd
[2024-01-24T03:06:24.577+0800] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-24T03:06:24.578+0800] {subprocess.py:93} INFO -   File "/home/am/project/scripts/train_model.py", line 9, in <module>
[2024-01-24T03:06:24.578+0800] {subprocess.py:93} INFO -     model.fit(df['id'].values.reshape(-1,1), df['counts'])
[2024-01-24T03:06:24.578+0800] {subprocess.py:93} INFO -   File "/home/am/project/venv/lib/python3.10/site-packages/sklearn/base.py", line 1351, in wrapper
[2024-01-24T03:06:24.578+0800] {subprocess.py:93} INFO -     return fit_method(estimator, *args, **kwargs)
[2024-01-24T03:06:24.578+0800] {subprocess.py:93} INFO -   File "/home/am/project/venv/lib/python3.10/site-packages/sklearn/linear_model/_base.py", line 578, in fit
[2024-01-24T03:06:24.578+0800] {subprocess.py:93} INFO -     X, y = self._validate_data(
[2024-01-24T03:06:24.579+0800] {subprocess.py:93} INFO -   File "/home/am/project/venv/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
[2024-01-24T03:06:24.579+0800] {subprocess.py:93} INFO -     X, y = check_X_y(X, y, **check_params)
[2024-01-24T03:06:24.579+0800] {subprocess.py:93} INFO -   File "/home/am/project/venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1208, in check_X_y
[2024-01-24T03:06:24.579+0800] {subprocess.py:93} INFO -     y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric, estimator=estimator)
[2024-01-24T03:06:24.579+0800] {subprocess.py:93} INFO -   File "/home/am/project/venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1218, in _check_y
[2024-01-24T03:06:24.579+0800] {subprocess.py:93} INFO -     y = check_array(
[2024-01-24T03:06:24.579+0800] {subprocess.py:93} INFO -   File "/home/am/project/venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1003, in check_array
[2024-01-24T03:06:24.579+0800] {subprocess.py:93} INFO -     _assert_all_finite(
[2024-01-24T03:06:24.579+0800] {subprocess.py:93} INFO -   File "/home/am/project/venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 126, in _assert_all_finite
[2024-01-24T03:06:24.579+0800] {subprocess.py:93} INFO -     _assert_all_finite_element_wise(
[2024-01-24T03:06:24.580+0800] {subprocess.py:93} INFO -   File "/home/am/project/venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 175, in _assert_all_finite_element_wise
[2024-01-24T03:06:24.580+0800] {subprocess.py:93} INFO -     raise ValueError(msg_err)
[2024-01-24T03:06:24.580+0800] {subprocess.py:93} INFO - ValueError: Input y contains NaN.
[2024-01-24T03:06:24.683+0800] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-24T03:06:24.802+0800] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/am/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-24T03:06:24.811+0800] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=train_model, execution_date=20240123T185533, start_date=20240123T190621, end_date=20240123T190624
[2024-01-24T03:06:24.852+0800] {standard_task_runner.py:100} ERROR - Failed to execute job 31 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 87908)
[2024-01-24T03:06:24.923+0800] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-01-24T03:06:25.022+0800] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
